[build]
  command = "pnpm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "24"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=4000"
    # in loving memory
    X-Clacks-Overhead = "GNU Terry Pratchett"
